### ISSUE TITLE
Azure Building Commits Twice

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/RadialGM#100]
Title ditto, it's building every commit to a pull request twice!
https://dev.azure.com/enigma-dev/RadialGM/_build/results?buildId=380&view=results
https://dev.azure.com/enigma-dev/RadialGM/_build/results?buildId=379&view=results

**Comment by fundies** [comment]
this is because youre using branches on main repo instead of pulling from your own fork

**Comment by RobertBColton** [comment]
This seems to have been fixed by df9c711320a5cbe32a1c4df4e1596e9411793821 and yes I mean this issue as well as the fact that it just wasn't triggering at all for fundies. I sent #104 and #103 and both were only triggered to build on Azure a single time.
https://dev.azure.com/enigma-dev/RadialGM/_build?definitionId=5&_a=summary

**Comment by RobertBColton** [comment]
Alright, I double checked by sending a second commit to both #104 and #103 and both triggered the CI again. However, this time they only triggered a single new build but under the same build instead of a whole new one. The original commits were both cancelled automatically. So this definitely seems to resolved.
