### ISSUE TITLE
Asset Background Problems

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/RadialGM#118]
I need to document a couple of issues that came up during implementation of the spatial hash for the room editor. They pertain mainly to the clipping of the painting for asset scroll area.

1) We are painting the room grid outside of the actual room, which LGM does not do, but I am totally fine with this. I think it's a good idea.
2) AssetScrollAreaBackground is not using its paint event at all, which tells it the current region being exposed that needs to be repainted. It's much more efficient for us to only paint what needs to be painted.
3) AssetView is not informed of the paint event by AssetScrollAreaBackground and thus has to completely guess which part of it is exposed for painting. This makes it difficult for the room view to know which window to query in the spatial hash.

**Comment by fundies** [comment]
well 2. relies on the hash to know if crapola is in the view...
