### ISSUE TITLE
Room Property Editor Has Gaps

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/RadialGM#127]
This is because the underlying proto field numbers are not contiguous. We are simply using the existing proto model to generate the property editor rows. There are several ways to address this problem.

* Flatten the existing proto model and or only the edit role. This could be problematic as we made the RepeatedMessageModel use column 0, a field number that can't exist in protobuf, to return the underlying proto model pointer.
* Provide a proxy model on top of the proto model which flattens the rows.
* Create a custom property editor view which knows how to skip non-existing rows in the proto model.

**Comment by fundies** [comment]
I think 2 is best but if its problematic 3 is ok too but 1 is just untenable

**Comment by RobertBColton** [comment]
This is resolved by #144 which is actually doing the first thing and flattening out the way we access the proto model.

**Comment by RobertBColton** [comment]
Closing as resolved by #144 super duper model.

**Comment by fundies** [comment]
dont close issues until a pr is merged

**Comment by RobertBColton** [comment]
Here's some doc links about the field order.
Serialization: https://developers.google.com/protocol-buffers/docs/encoding#order
