### ISSUE TITLE
Feature Ideas

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/RadialGM#14]
- [ ] Shortcut to open a resource when highlighting it in the code editor
- [ ] Should be able to right click and open resources in external editor directly from the tree, bypassing the internal editor
- [ ] Anywhere there's a resource picker, such as dnd window or object parent, you should also be able to open the resource window just by clicking it
- [ ] Should have modular way for a resource to provide a tooltip to preview its contents when hovering over its node in the tree, i.e. hover over script would show tooltip with first few lines of code
- [ ] Import/export dialog with tree merge
- [ ] Game setting for starting room

**Comment by 9Morello** [comment]
It would be cool to have it automatically check for changed files, so it plays nice with 3rd-party editors (like GMEdit).

If possible, it could be support themes (for the IDE and the code editor).

**Comment by RobertBColton** [comment]
@9Morello Don't worry, we are going to add that and almost did the other day but are working on more important structural things first. The new backend, which now handles project loading, is intended to handle all of the GM formats, but so far we only have GMX. However, it is already dynamic enough that it can load a single resource without having to load an entire project:
https://github.com/enigma-dev/enigma-dev/blob/c4a6f3c7b7ca7a2404cd6b88e5489575ac4fa3be/CommandLine/libGMX/gmx.cpp#L506

We will be adding GMS2's format using the exact same code (I'm going to rename gmx.cpp) because the readers for both will be like %99 identical. Then we just have to add a file system watcher in RGM to reload the tree. I'll let you know more as we get it done and closer to the beta.

**Comment by 9Morello** [comment]
That's nice to hear. Do you guys have any idea about how the Room Editor will look like? Since GM's own editor is a pain to work it, maybe it's a good idea to take inspiration from [Tiled](http://www.mapeditor.org/) or [GMARE](https://archive.codeplex.com/?p=gmare).

Is anything going to change in ENIGMA for this IDE? You mentioned support for GMS2 format, so I imagine you guys will add support for GMS2's GML?

**Comment by RobertBColton** [comment]
Don't worry, we're are taking a lot of the innovative ideas over the past several years of game development/engines/tools/etc. Yes, a lot of things are going to change ENIGMA side.

The main reason we are using protocol buffers by Google for the project serialization (which actually makes GMX easier to load as you can see) is that it is backwards compatible. This means if we go to add or change resources in anyway, you don't need to worry about old versions of ENIGMA not understanding your project files or deleting things. It also means I don't have to bug people to download the latest plugin because of a minor change in ENIGMA's backend (most of the backend, including the C interfaces for resources, we plan to delete).

You can review the changes we've made so far to achieve what we're currently doing in the pull request from protobuf branch on ENIGMA:
https://github.com/enigma-dev/enigma-dev/pull/1179

Tonight I was designing a plugin API for RadialGM to also have its own plugins to extend the UI with custom editors and such. I spent most of the night creating the very first plugin, the one that communicates to our gRPC server in the CLI allowing you to run/debug/compile:
![Server Plugin](https://user-images.githubusercontent.com/3212801/37946995-9624da30-3156-11e8-85fc-9fdc4727fe3f.png)

This is the first change we will be announcing, we plan on moving the lgmplugin for ENIGMA to use this server (so it no longer has the 32bit/64bit problem and also crashes less because compile is put into a separate process). This will remove the dependency on JNA from LateralGM, which we also intend to delete.

I hope you find this interesting, but I encourage you to just stay tuned for more now I don't want to say much else.

**Comment by 9Morello** [comment]
Looking good. I feel the biggest issue with ENIGMA/LateralGM was stability and you guys seem to be working on that.

I'll definitely stay tuned and give it a try as soon as it's out. :)
