### ISSUE TITLE
Narrow 'Create Resource' list based on folder 

### ISSUE THREAD

**Issue by KartikShrivastava** [enigma-dev/RadialGM#225]
Hi,
`Create Resource` menu in RGM shows whole list of resources ignoring the folder type user has clicked on:

![image](https://user-images.githubusercontent.com/26518513/161009124-548a7a32-51af-49cf-97f5-6f6a3e8b55c3.png)

Taking reference of LGM, it shows only desired `Create Resource` button instead of a nested list:
![image](https://user-images.githubusercontent.com/26518513/161009691-2387b971-b7b7-4e8c-960d-55095777a833.png)

**Comment by fundies** [comment]
EGM doesn't force that GM-Style project organization on you. It's there as a default but you can organize your project however you want. There are no special folders.

**Comment by KartikShrivastava** [comment]
Got it. I felt it was bug as it also let us add different type of resource into a different folder name.

**Comment by RobertBColton** [comment]
There will maybe be a logical view added that will show you the classic separated view that you can toggle between. Regardless, even then the physical restriction is no longer necessary.
