### ISSUE TITLE
Model Index Validity Checking

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/RadialGM#62]
I want to talk about #61 which was just merged. What daz did there does in deed fix the crash when creating a new sprite by checking if the model index is valid in the sprite model. However, it did not fix where our code was actually invalid, which is in the sprite editor.
https://github.com/enigma-dev/RadialGM/blob/8fdcf5fd5c018c18fc782a91c9b0366a422a3fee/Editors/SpriteEditor.cpp#L15

What I think we need to consider here is if we should be checking if the model indexes are valid in our data models at runtime. This is what is done in official Qt examples. However, I am concerned it will allow us to get away with writing buggy/incorrect code and have it going unnoticed. What I think should be considered is that we move these model index validity checks to the debug build and change them to assertions.

**Comment by dazappa** [comment]
OK if we are confident we should always pass valid indexes to the models, I like your idea. If you fix the underlying issue of why that index was invalid, I could probably go through all the models and add the asserts to the model::data functions.

**Comment by RobertBColton** [comment]
Ok, Rusky basically did reach the same conclusion I did. However, now I think I've changed my opinion. I think I want to actually do this an unconventional way.

Being that this is a C++ IDE, and naturally more prone to crashes than LateralGM ever would be. I think I am in favor of [defensive programming](https://en.wikipedia.org/wiki/Defensive_programming). And I think we should turn the valid checks into assertions for debug mode. If there's an easy way for us to get that behavior, without turning all of these checks into four lines, I think that's what we should do.

I am going to wait and run this yet by Josh.

**Comment by JoshDreamland** [comment]
The IDE is already heavily invested in Google technology; consider using a logger. Alternatively, consider using your own logging system. When you're supposed to get a valid ID, but do not, log it. 

Surface these error messages in a debug console. Have an icon that opens the debug console. When it has errors in it, change the icon to include a red dot, possibly including a number. When the issue is severe, display a message (like in LGM). Offer Help→Report a problem, and have it include a summary of the log in the suggested bug report.

Caveat: This log could fill up FAST. Mitigate problems with enormous quantities of error messages. Reduce duplicate log messages by digesting them to `{ first timestamp, last timestamp, count }`. Use the source file + line number to identify these. *Include that in the log.*

**Comment by RobertBColton** [comment]
I've prepared #63 which does exactly what Josh said. I log the invalid index events in debug and release mode. Are you goes ok with how much fat this may add around RGM's waistline? What do you guys think about the places we aren't checking yet (like NULL ptrs and such)? Should we just continue to spread this convention to the other classes over time?

**Comment by RobertBColton** [comment]
Also, one more point I could use feedback on. It is possible for me to put the conditions of the logging into `Q_ASSERT` and that means if you wanted to compile RGM with the verbose logging removed, you'd simply set the flag `QT_NO_DEBUG`.
https://doc.qt.io/qt-5/debug.html

**Comment by RobertBColton** [comment]
We could additionally wrap groups of defensive logging assertions that we make in `#ifdef QT_NO_DEBUG`. This would allow you to compile a version of RGM without the verbose logging and schizophrenic condition checks. Really though, why would you ever want a version of RGM like that?

**Comment by RobertBColton** [comment]
Alright we've taken care of it with #63. I now expect the new `Components/Logger.h` macros to be used everywhere and anywhere there's a model index, pointer, or some potential for crashing or other incorrect behavior. All of the Qt debugging macros are now reserved for internal RGM issues only. Other forms of logging should use new instances of the Qt logging services if needed.
