### ISSUE TITLE
Azure Artifact Missing Executable Properties

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/RadialGM#99]
So somehow fundies is setting the ENIGMA icon the Azure exe, but when you launch RGM there's no Window icon in the top right, just the Win32 default. 

We also aren't setting the copyright or the company like we do in the pro file.
https://github.com/enigma-dev/RadialGM/blob/8960e221a81ef2cafae39461cd3fa4b6722a6b52/RadialGM.pro#L18

**Comment by RobertBColton** [comment]
Seems I discovered the missing icon problem is coming from fundies installer stuff.
https://stackoverflow.com/a/55838741

**Comment by fundies** [comment]
nsis stuffs is here https://github.com/enigma-dev/RadialGM/blob/master/cmake-package/CMakeLists.txt
